### ISSUE TITLE
Error with Jruby 

### ISSUE THREAD

**Issue by deekoder** [dylanvaughn/aws_cf_signer#10]
Hello I am not sure if this gem is unsupported on jruby. But i keep getting this error. No insight on Stackoverflow.

NoMethodError: undefined method `=~' for #<Pathname:0x79d63a4f>
                              initialize at  /~/.rvm/gems/jruby-1.7.19/gems/aws_cf_signer-0.1.3/lib/aws_cf_signer.rb:10

**Comment by dylanvaughn** [comment]
Hi - I would like it to be supported on jruby - what version of jruby are you running?

**Comment by dylanvaughn** [comment]
Oh I see - 1.7.19 - will take a look

**Comment by dylanvaughn** [comment]
@deekoder I think the issue is not jRuby but it seems you are passing a Pathname object to the init method instead of a string of the path to the key or pem.
