### ISSUE TITLE
`sign` will used canned policy if `policy_options` only contains `:ending` and `:resource`

### ISSUE THREAD

**Issue by juliancooper** [dylanvaughn/aws_cf_signer#8]
When using this gem to sign a CF URL for a resource with a wildcard and an expiration time, but no other options, the `sign` method will create a canned policy querystring, rather than a custom policy query string.

**Comment by dylanvaughn** [comment]
Thanks for the report - I believe I have fixed this here:

https://github.com/dylanvaughn/aws_cf_signer/pull/9

If possible can you try with the branch to see if it fixes the issue?

**Comment by dylanvaughn** [comment]
Hi @juliancooper I merged my PR that I hope fixes this - closing this issue for now.
